name: Business Task
description: Create a task for the Business/Marketing team (Sponsorship, Outreach, Finance)
title: "[BIZ]: "
labels: ["business", "marketing"]
body:
  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: What needs to be done?
      placeholder: "e.g., Draft sponsorship email for MDA..."
    validations:
      required: true
  - type: input
    id: deadline
    attributes:
      label: Deadline
      placeholder: "YYYY-MM-DD"
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What does "Done" look like?
      placeholder: "- [ ] Email draft reviewed by DJ\n- [ ] Sent to 5 contacts"
